### PR TITLE
change gsettings path for dconf to  a valid path

### PR DESCRIPTION
**Pull request by raveit65**
that's all for migrate to gsetting target.

### CODE REVIEW

**Comment by stefano-k** [comment]
can you change to "/org/mate/bluetooth-manager/" to avoid mate duplication? thanks :)

**Comment by raveit65** [comment]
which mate duplication, but you're the boss :)

**Comment by stefano-k** [comment]
lol... I mean mate/mate. there is still org/mate/mate-bluetooth-sendto to rename to org/mate/bluetooth-sendto
thanks!

**Comment by raveit65** [comment]
hmm, what should i change to avoid confuision?

mate-bluetouth.sendto or mate-bluetouth- manager

**Comment by stefano-k** [comment]
org/mate/mate-bluetooth-sendto => org/mate/bluetooth-sendto

**Comment by raveit65** [comment]
here we go.....

**Pull request merged**
