### PR TITLE
Merge with upstream

### PR DESCRIPTION
**Pull request by benpicco**
Pull in all gnome 2.32 fixes after the mate fork, without the translation updates

### CODE REVIEW

**Comment by stefano-k** [comment]
Thank you benpicco. I added both patches except for .gitignore.

https://github.com/mate-desktop/mate-bluetooth/commit/686235b03352780119f54ecba97034350c10e287
https://github.com/mate-desktop/mate-bluetooth/commit/f0b1476ec9c89730abb13f0105c8af74dc73d500

**Comment by benpicco** [comment]
Why are you not using git but copy & paste the patches?

**Comment by stefano-k** [comment]
to avoid .gitignore commit :)

**Comment by benpicco** [comment]
What's the problem with .gitignore?

**Pull request closed without merging**
